name: Publish Benchmark Snapshot (Template)

on:
  workflow_dispatch:
    inputs:
      snapshot_id:
        description: "Opaque snapshot id (immutable)"
        required: true
        default: "snapshot-YYYY-MM-DD"
      nextstat_wheel_url:
        description: "URL to the pinned NextStat wheel (.whl) being measured"
        required: true
      nextstat_wheel_sha256:
        description: "SHA-256 of the wheel file (hex)"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install harness deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r env/python/requirements.txt

      - name: Install pinned NextStat wheel
        env:
          NEXTSTAT_WHEEL_URL: ${{ inputs.nextstat_wheel_url }}
          NEXTSTAT_WHEEL_SHA256: ${{ inputs.nextstat_wheel_sha256 }}
        run: |
          set -euo pipefail
          mkdir -p tmp
          curl -L "${NEXTSTAT_WHEEL_URL}" -o tmp/nextstat.whl
          echo "${NEXTSTAT_WHEEL_SHA256}  tmp/nextstat.whl" | sha256sum -c -
          python -m pip install tmp/nextstat.whl

      - name: Run suite(s)
        run: |
          python scripts/publish_snapshot.py \
            --snapshot-id "${{ inputs.snapshot_id }}" \
            --deterministic \
            --suite "public-benchmarks" \
            --nextstat-wheel tmp/nextstat.whl \
            --fit --fit-repeat 3

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-${{ inputs.snapshot_id }}
          path: manifests/snapshots/${{ inputs.snapshot_id }}/
