name: Publish Benchmark Snapshot (Template)

on:
  workflow_dispatch:
    inputs:
      snapshot_id:
        description: "Opaque snapshot id (immutable)"
        required: true
        default: "snapshot-YYYY-MM-DD"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r env/python/requirements.txt
          echo "TODO: install a pinned NextStat wheel artifact"

      - name: Run suite(s)
        run: |
          python scripts/publish_snapshot.py \
            --snapshot-id "${{ inputs.snapshot_id }}" \
            --deterministic \
            --fit --fit-repeat 3

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-${{ inputs.snapshot_id }}
          path: manifests/snapshots/${{ inputs.snapshot_id }}/
