test_that("nextstat_kalman runs local level model", {
  set.seed(42)
  y <- cumsum(rnorm(50, sd = 0.2)) + rnorm(50, sd = 0.5)
  F <- matrix(1, 1, 1)
  H <- matrix(1, 1, 1)
  Q <- matrix(0.1, 1, 1)
  R <- matrix(0.25, 1, 1)
  kf <- nextstat_kalman(y, F, H, Q, R)
  expect_type(kf, "list")
  expect_true(is.finite(kf$log_likelihood))
  expect_length(kf$filtered_means, length(y))
  expect_length(kf$smoothed_means, length(y))
})

test_that("nextstat_garch fits return series", {
  set.seed(42)
  rets <- rnorm(200, sd = 0.01)
  g <- nextstat_garch(rets)
  expect_type(g, "list")
  expect_true(is.finite(g$log_likelihood))
  expect_length(g$conditional_variance, length(rets))
  expect_true(g$omega > 0)
  expect_true(g$alpha >= 0)
  expect_true(g$beta >= 0)
})

test_that("nextstat_sv fits return series", {
  set.seed(42)
  rets <- rnorm(200, sd = 0.01)
  sv <- nextstat_sv(rets)
  expect_type(sv, "list")
  expect_true(is.finite(sv$log_likelihood))
  expect_length(sv$smoothed_sigma, length(rets))
  expect_true(sv$sigma > 0)
})
