name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I'd like NextStat to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: I also considered...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      render: rust

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature relate to?
      options:
        - Core (ns-core)
        - Compute Backends (ns-compute)
        - Statistical Inference (ns-inference)
        - Format Translation (ns-translate)
        - Visualization (ns-viz)
        - CLI (ns-cli)
        - Python Bindings (ns-py)
        - Documentation
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority (your opinion)
      description: How important is this feature to you?
      options:
        - Critical - blocking my work
        - High - would significantly improve my workflow
        - Medium - nice to have
        - Low - minor improvement

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
