#!/usr/bin/env python3
# Generated by scripts/generate_agent_bootstrap_packs.py. Do not edit directly.
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

CLIENT = "gemini"
TRANSPORT = "local"
TITLE = "Gemini function-calling"
PACK_RELATIVE_PATH = "docs/specs/agent_bootstrap/nextstat_gemini_local_bootstrap_v1.json"
DEFAULT_MODEL = "gemini-2.5-pro"
PROVIDER_PAYLOAD_KEY = "function_declarations"
PROVIDER_PROMPT_KEY = "prompt"
PROVIDER_INSTRUCTION_KEY = "system_instruction"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _load_pack() -> dict:
    return json.loads((_repo_root() / PACK_RELATIVE_PATH).read_text(encoding="utf-8"))


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=f"Runnable NextStat {CLIENT} {TRANSPORT} provider example generated from canonical bootstrap packs."
    )
    parser.add_argument("--model", default=DEFAULT_MODEL, help="Provider model name.")
    parser.add_argument(
        "--prompt",
        default="Audit the available NextStat tools and choose the best matching recipe.",
        help="Provider prompt or task seed.",
    )
    parser.add_argument("--recipe-id", default=None, help="Optional recipe id filter.")
    parser.add_argument(
        "--print-pack",
        action="store_true",
        help="Print the generated bootstrap pack without loading a live NextStat descriptor.",
    )
    parser.add_argument(
        "--server-url",
        default=os.environ.get("NEXTSTAT_TOOLS_SERVER_URL"),
        help="nextstat-server URL for server transport.",
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("NEXTSTAT_TOOLS_API_KEY") or os.environ.get("NEXTSTAT_SERVER_API_KEY"),
        help="Bearer API key for server transport.",
    )
    return parser


def _select_recipes(pack: dict, recipe_id: str | None) -> list[dict]:
    recipes = pack["recipes"]
    if recipe_id is None:
        return recipes
    selected = [recipe for recipe in recipes if recipe["id"] == recipe_id]
    if not selected:
        raise SystemExit(f"Unknown recipe id: {recipe_id}")
    return selected


def _build_request(pack: dict, descriptor: dict, model: str, prompt: str, recipes: list[dict]) -> dict:
    return {
        "provider": CLIENT,
        "transport": TRANSPORT,
        "title": TITLE,
        "model": model,
        PROVIDER_PROMPT_KEY: prompt,
        PROVIDER_INSTRUCTION_KEY: "\n".join(pack["instructions"]),
        PROVIDER_PAYLOAD_KEY: descriptor["tools"],
        "guidance_hints": descriptor["guidance"]["hints"],
        "recipe_ids": [recipe["id"] for recipe in recipes],
        "recipes": recipes,
        "bootstrap_snippet": pack["snippets"]["bootstrap"],
        "execution_loop_snippet": pack["snippets"]["execution_loop"],
        "references": pack["references"],
    }


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()
    pack = _load_pack()
    if args.print_pack:
        print(json.dumps(pack, indent=2, sort_keys=True))
        return 0

    from nextstat.tools import get_toolkit_descriptor

    descriptor = get_toolkit_descriptor(transport="local")

    recipes = _select_recipes(pack, args.recipe_id)
    request = _build_request(pack, descriptor, args.model, args.prompt, recipes)
    print(json.dumps(request, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

