#!/usr/bin/env python3
# Generated by scripts/generate_agent_bootstrap_packs.py. Do not edit directly.
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

CLIENT = "mcp"
TRANSPORT = "local"
TITLE = "MCP tool server"
PACK_RELATIVE_PATH = "docs/specs/agent_bootstrap/nextstat_mcp_local_bootstrap_v1.json"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _load_pack() -> dict:
    return json.loads((_repo_root() / PACK_RELATIVE_PATH).read_text(encoding="utf-8"))


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=f"Runnable NextStat MCP {TRANSPORT} bootstrap generated from canonical packs."
    )
    parser.add_argument("--recipe-id", default=None, help="Optional recipe id filter.")
    parser.add_argument(
        "--print-pack",
        action="store_true",
        help="Print the generated bootstrap pack without loading a live NextStat descriptor.",
    )
    parser.add_argument(
        "--server-url",
        default=os.environ.get("NEXTSTAT_TOOLS_SERVER_URL"),
        help="nextstat-server URL for server transport.",
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("NEXTSTAT_TOOLS_API_KEY") or os.environ.get("NEXTSTAT_SERVER_API_KEY"),
        help="Bearer API key for server transport.",
    )
    return parser


def _select_recipes(pack: dict, recipe_id: str | None) -> list[dict]:
    recipes = pack["recipes"]
    if recipe_id is None:
        return recipes
    selected = [recipe for recipe in recipes if recipe["id"] == recipe_id]
    if not selected:
        raise SystemExit(f"Unknown recipe id: {recipe_id}")
    return selected


def _build_config(pack: dict, descriptor: dict, mcp_tools: list[dict], recipes: list[dict], dispatch: dict) -> dict:
    return {
        "client": CLIENT,
        "transport": TRANSPORT,
        "title": TITLE,
        "tool_server_name": "nextstat" if TRANSPORT == "local" else "nextstat-server",
        "mcp_tools": mcp_tools,
        "guidance_hints": descriptor["guidance"]["hints"],
        "recipe_ids": [recipe["id"] for recipe in recipes],
        "recipes": recipes,
        "bootstrap_snippet": pack["snippets"]["bootstrap"],
        "execution_loop_snippet": pack["snippets"]["execution_loop"],
        "references": pack["references"],
        "dispatch": dispatch,
    }


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()
    pack = _load_pack()
    if args.print_pack:
        print(json.dumps(pack, indent=2, sort_keys=True))
        return 0

    from nextstat.tools import get_mcp_tools, get_toolkit_descriptor

    descriptor = get_toolkit_descriptor(transport="local")
    mcp_tools = get_mcp_tools()
    dispatch = {
        "mode": "handle_mcp_call",
        "entrypoint": "nextstat.tools.handle_mcp_call(name, arguments)",
    }

    recipes = _select_recipes(pack, args.recipe_id)
    config = _build_config(pack, descriptor, mcp_tools, recipes, dispatch)
    print(json.dumps(config, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

